In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl as op

In [3]:
df=pd.read_csv("resume_dataset_200k_enhanced.csv")

In [4]:
df.head()

,candidate_id,age,education_level,university_tier,cgpa,internships,projects,programming_languages,certifications,experience_years,hackathons,research_papers,skills_score,hired,soft_skills_score,resume_length_words,company_type
0,1,27,Bachelors,Tier 2,8.16,2,7,2,2,0.33,0,0,21.0,1,5.62,409,MNC
1,2,24,Bachelors,Tier 3,6.35,3,2,2,2,4.99,0,0,11.0,1,9.66,237,Startup
2,3,33,Bachelors,Tier 3,7.78,0,2,4,2,0.93,0,0,15.0,1,8.12,435,Startup
3,4,31,Masters,Tier 3,6.92,2,1,4,1,0.37,0,0,11.5,1,7.19,340,MNC
4,5,28,Masters,Tier 2,8.24,3,0,1,2,0.33,0,0,5.0,0,4.09,371,Mid-size

In [5]:
df.tail()

,candidate_id,age,education_level,university_tier,cgpa,internships,projects,programming_languages,certifications,experience_years,hackathons,research_papers,skills_score,hired,soft_skills_score,resume_length_words,company_type
199995,199996,22,Bachelors,Tier 3,7.32,2,3,1,1,3.81,1,0,10.5,0,7.36,221,MNC
199996,199997,28,Masters,Tier 1,8.47,2,2,3,0,0.35,0,0,10.0,1,7.40,350,Mid-size
199997,199998,29,Bachelors,Tier 1,6.66,1,3,5,1,5.32,0,0,17.5,0,4.35,362,MNC
199998,199999,34,Masters,Tier 2,8.17,3,3,1,0,0.38,0,0,8.0,0,7.57,373,MNC
199999,200000,31,Bachelors,Tier 2,6.57,2,1,5,0,1.08,0,0,12.0,0,3.01,193,Startup

In [6]:
df.shape

(200000, 17)

In [7]:
df.columns

Index(['candidate_id', 'age', 'education_level', 'university_tier', 'cgpa',
       'internships', 'projects', 'programming_languages', 'certifications',
       'experience_years', 'hackathons', 'research_papers', 'skills_score',
       'hired', 'soft_skills_score', 'resume_length_words', 'company_type'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   candidate_id           200000 non-null  int64
 1   age                    200000 non-null  int64
 2   education_level        200000 non-null  str
 3   university_tier        200000 non-null  str
 4   cgpa                   200000 non-null  float64
 5   internships            200000 non-null  int64
 6   projects               200000 non-null  int64
 7   programming_languages  200000 non-null  int64
 8   certifications         200000 non-null  int64
 9   experience_years       200000 non-null  float64
 10  hackathons             200000 non-null  int64
 11  research_papers        200000 non-null  int64
 12  skills_score           200000 non-null  float64
 13  hired                  200000 non-null  int64
 14  soft_skills_score      200000 non-null  float64
 15  resume_length_words    200000 non-null  int64
 16  company_type           200000 non-null  str
dtypes: float64(4), int64(10), str(3)
memory usage: 29.7 MB

In [9]:
df.describe()

,candidate_id,age,cgpa,internships,projects,programming_languages,certifications,experience_years,hackathons,research_papers,skills_score,hired,soft_skills_score,resume_length_words
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,100000.500000,27.511705,7.499323,1.503015,2.996240,3.004420,1.000985,1.499030,0.498005,0.201950,14.000803,0.706060,6.502866,449.206975
std,57735.171256,4.030684,0.800952,1.225373,1.731104,1.412229,1.002217,1.497477,0.706773,0.448806,4.766263,0.455566,2.019637,120.103065
min,1.000000,21.000000,4.150000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,-79.000000
25%,50000.750000,24.000000,6.960000,1.000000,2.000000,2.000000,0.000000,0.430000,0.000000,0.000000,10.500000,0.000000,4.750000,368.000000
50%,100000.500000,28.000000,7.500000,1.000000,3.000000,3.000000,1.000000,1.040000,0.000000,0.000000,14.000000,1.000000,6.510000,449.000000
75%,150000.250000,31.000000,8.040000,2.000000,4.000000,4.000000,2.000000,2.080000,1.000000,0.000000,17.000000,1.000000,8.250000,530.000000
max,200000.000000,34.000000,11.230000,10.000000,14.000000,5.000000,8.000000,23.550000,6.000000,5.000000,38.500000,1.000000,10.000000,956.000000

In [11]:
df.dtypes

candidate_id               int64
age                        int64
education_level              str
university_tier              str
cgpa                     float64
internships                int64
projects                   int64
programming_languages      int64
certifications             int64
experience_years         float64
hackathons                 int64
research_papers            int64
skills_score             float64
hired                      int64
soft_skills_score        float64
resume_length_words        int64
company_type                 str
dtype: object

In [12]:
df.isnull().sum()

candidate_id             0
age                      0
education_level          0
university_tier          0
cgpa                     0
internships              0
projects                 0
programming_languages    0
certifications           0
experience_years         0
hackathons               0
research_papers          0
skills_score             0
hired                    0
soft_skills_score        0
resume_length_words      0
company_type             0
dtype: int64

In [13]:
(df.isnull().sum()/len(df))*100

candidate_id             0.0
age                      0.0
education_level          0.0
university_tier          0.0
cgpa                     0.0
internships              0.0
projects                 0.0
programming_languages    0.0
certifications           0.0
experience_years         0.0
hackathons               0.0
research_papers          0.0
skills_score             0.0
hired                    0.0
soft_skills_score        0.0
resume_length_words      0.0
company_type             0.0
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [candidate_id, age, education_level, university_tier, cgpa, internships, projects, programming_languages, certifications, experience_years, hackathons, research_papers, skills_score, hired, soft_skills_score, resume_length_words, company_type]
Index: []